# Generated by Django 5.2.5 on 2025-09-01 04:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'carteras',
            },
        ),
        migrations.CreateModel(
            name='CarteraMiembro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('gestor', 'Gestor'), ('operador', 'Operador')], default='gestor', max_length=16)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.cartera')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_cartera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cartera_miembros',
            },
        ),
        migrations.AddField(
            model_name='cartera',
            name='miembros',
            field=models.ManyToManyField(related_name='carteras_miembro', through='core.CarteraMiembro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=128, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=64)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('direccion_laboral', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('red_social', models.CharField(blank=True, default='', max_length=255)),
                ('foto_cliente', models.ImageField(blank=True, null=True, upload_to='clientes/%Y/%m/%d')),
                ('foto_dni_1', models.ImageField(blank=True, null=True, upload_to='clientes/%Y/%m/%d')),
                ('foto_dni_2', models.ImageField(blank=True, null=True, upload_to='clientes/%Y/%m/%d')),
                ('garante_identificacion', models.CharField(blank=True, default='', max_length=128)),
                ('garante_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('garante_apellido', models.CharField(blank=True, default='', max_length=255)),
                ('garante_direccion', models.CharField(blank=True, default='', max_length=255)),
                ('garante_telefono', models.CharField(blank=True, default='', max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clientes',
                'indexes': [models.Index(fields=['identificacion'], name='idx_clientes_identificacion'), models.Index(fields=['email'], name='idx_clientes_email')],
            },
        ),
        migrations.AddIndex(
            model_name='carteramiembro',
            index=models.Index(fields=['cartera', 'usuario'], name='idx_cartera_usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='carteramiembro',
            unique_together={('cartera', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='cartera',
            index=models.Index(fields=['nombre'], name='idx_carteras_nombre'),
        ),
    ]
