# Generated by Django 5.2.5 on 2025-09-09 03:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'carteras',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('capital_programado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes_programado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capital_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interes_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('mora', 'Mora'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=16)),
            ],
            options={
                'db_table': 'cuotas',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(blank=True, default='', max_length=50)),
                ('observacion', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='CarteraMiembro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('gestor', 'Gestor'), ('operador', 'Operador')], default='gestor', max_length=16)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.cartera')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_cartera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cartera_miembros',
            },
        ),
        migrations.AddField(
            model_name='cartera',
            name='miembros',
            field=models.ManyToManyField(related_name='carteras_miembro', through='core.CarteraMiembro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=128, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=64)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('direccion_laboral', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('red_social', models.CharField(blank=True, default='', max_length=255)),
                ('foto_cliente', models.ImageField(blank=True, null=True, upload_to='clientes/%Y/%m/%d')),
                ('foto_dni_1', models.ImageField(blank=True, null=True, upload_to='clientes/%Y/%m/%d')),
                ('foto_dni_2', models.ImageField(blank=True, null=True, upload_to='clientes/%Y/%m/%d')),
                ('garante_identificacion', models.CharField(blank=True, default='', max_length=128)),
                ('garante_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('garante_apellido', models.CharField(blank=True, default='', max_length=255)),
                ('garante_direccion', models.CharField(blank=True, default='', max_length=255)),
                ('garante_telefono', models.CharField(blank=True, default='', max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clientes',
                'indexes': [models.Index(fields=['identificacion'], name='idx_clientes_identificacion'), models.Index(fields=['email'], name='idx_clientes_email')],
            },
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128, unique=True)),
                ('tasa_decimal', models.DecimalField(decimal_places=6, help_text='0.20 = 20%', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intereses',
                'indexes': [models.Index(fields=['nombre'], name='idx_intereses_nombre')],
            },
        ),
        migrations.CreateModel(
            name='PagoDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capital_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interes_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='core.cuota')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pago')),
            ],
            options={
                'db_table': 'pagos_detalle',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuotas_totales', models.PositiveIntegerField(help_text='Número total de cuotas')),
                ('frecuencia', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='mensual', max_length=16)),
                ('primera_cuota_fecha', models.DateField(help_text='Fecha del primer cobro')),
                ('fecha_desembolso', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('mora', 'Mora'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('saldo_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_interes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='core.cartera')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prestamos', to='core.cliente')),
                ('interes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='core.interes')),
            ],
            options={
                'db_table': 'prestamos',
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.prestamo'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.prestamo'),
        ),
        migrations.AddIndex(
            model_name='carteramiembro',
            index=models.Index(fields=['cartera', 'usuario'], name='idx_cartera_usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='carteramiembro',
            unique_together={('cartera', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='cartera',
            index=models.Index(fields=['nombre'], name='idx_carteras_nombre'),
        ),
        migrations.AddIndex(
            model_name='pagodetalle',
            index=models.Index(fields=['cuota'], name='idx_pago_detalle_cuota'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['cartera'], name='idx_prestamos_cartera'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['cliente'], name='idx_prestamos_cliente'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['estado'], name='idx_prestamos_estado'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['created_at'], name='idx_prestamos_created'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['prestamo', 'fecha_pago'], name='idx_pagos_prestamo_fecha'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['prestamo', 'numero'], name='idx_cuota_prestamo_num'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['prestamo', 'estado'], name='idx_cuota_prestamo_estado'),
        ),
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('prestamo', 'numero')},
        ),
    ]
