# Generated by Django 5.2.5 on 2025-09-01 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes_mensual', models.DecimalField(decimal_places=3, max_digits=6)),
                ('plazo_meses', models.PositiveIntegerField()),
                ('fecha_desembolso', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('activo', 'Activo'), ('mora', 'Mora'), ('cancelado', 'Cancelado'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='core.cartera')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prestamos', to='core.cliente')),
            ],
            options={
                'db_table': 'prestamos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capital_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interes_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mora_pagada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metodo_pago', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.prestamo')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['cartera'], name='idx_prestamos_cartera'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['cliente'], name='idx_prestamos_cliente'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['estado'], name='idx_prestamos_estado'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['created_at'], name='idx_prestamos_created'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['prestamo', 'fecha_pago'], name='idx_pagos_prestamo_fecha'),
        ),
    ]
