# Generated by Django 5.2.5 on 2025-09-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prestamo_pago_prestamo_idx_prestamos_cartera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='interes_mensual',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='monto',
            field=models.DecimalField(decimal_places=1, max_digits=12),
        ),
    ]
